server:
  port: 8080

spring:
  datasource:
    default:
      name: datasource
      url: jdbc:mysql://192.168.3.17:3306/cat?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: rootroot
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    risk:
      name: datasource
      url: jdbc:mysql://192.168.3.17:3306/mis?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: rootroot
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    raptor:
	  name: datasource
	  url: jdbc:mysql://mo9simulation.mysql.rds.aliyuncs.com:3306/raptor?useUnicode=true&characterEncoding=utf-8&useSSL=true
	  username: dev
	  password: dev@mo9.com
	  type: com.alibaba.druid.pool.DruidDataSource
	  driverClassName: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 10000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    username: user_cln
    password: mo9.com
    addresses: 192.168.3.191:5672
    virtual-host: /
    publisher-confirms: true
    mq-exchange: E.CLONE.TOPIC.RAPTOR.ALL
    loanMq:
      queue: Q.CLONE.DURABLE.RAPTOR.CAT.LOAN
      receivedAllRoutingKey: LOAN_TAG
    repayMq:
      queue: Q.CLONE.DURABLE.RAPTOR.CAT.REPAY
      orderRepaymentRoutingKey: REPAY_TAG
#        listener:
#          concurrency: 5
#          max-concurrency: 10
#          #acknowledge-mode: manual

redis:
  default:
    database: 20
    host: 192.168.3.31
    password: dev@Mo9.com
    port: 6379
  nest:
    database: 6
    host: 192.168.3.31
    password: dev@Mo9.com
    port: 6379
  ssl: false
  timeout: 20000
  maxTotal: 50
  maxWait: 10000
  maxIdle: 10x
  minIdle: 0

datacenterId: 1
machineId: 1

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cat.module

nest:
  url: https://libra.alpha.mo9.com/nestApi/
  key: 43113fd8d67c4e0aa1eb3e857358ab3c
  secret: b49bdfc7fab246968806007696fe65dc
  code: Cat
  group: CatGroup
  mode: ALONE
  exclude:
    urls: /cat/account/login, /cat/account/register,/cat/account/send_validate_code

feign:
  httpclient:
    enabled: true
feignClient:
  suona:
    url:  https://suona.alpha.mo9.com/suonaApi
    systemCode: BOURSE
    captchaTemplateCode: GENERAL_CAPTCHA

logging:
  level:
    root: debug
    org.springframework.amqp: info
    com.cat.manager.MessageSender: debug
