server:
  port: 8080

spring:
  datasource:
    default:
      name: datasource
      url: jdbc:mysql://127.0.0.1:3306/cat?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    risk:
      name: datasource
      url: jdbc:mysql://127.0.0.1:3306/mis?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 10000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
        username: user_cln
        password: mo9.com
        addresses: 192.168.3.191:5672
        virtual-host: /
        publisher-confirms: true
        mq-exchange: E.CLONE.TOPIC.RAPTOR.ALL
        listener:
          concurrency: 5
          max-concurrency: 10
          #acknowledge-mode: manual

redis:
  ssl: false
  database: 0
  host: 127.0.0.1
  password: 123456
  port: 6379
  timeout: 20000
  maxTotal: 50
  maxWait: 10000
  maxIdle: 10
  minIdle: 0

datacenterId: 1
machineId: 1

rabbit:
  customerAndOrder:
    receivedAllRoutingKey: LOAN_TAG
    orderRepaymentRoutingKey: REPAY_TAG
    queue: Q.CLONE.DURABLE.RAPTOR.MIS

httpclient:
  pool:
    maxTotal: 500
    defaultMaxPerRoute: 200