server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cat?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    maxActive: 50
    initialSize: 10
    maxWait: 10000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none

redis:
  ssl: false
  database: 0
  host: 127.0.0.1
  password: 123456
  port: 6379
  timeout: 20000
  maxTotal: 50
  maxWait: 10000
  maxIdle: 10
  minIdle: 0

datacenterId: 1
machineId: 1